Fix mypy error since version 1.20.0
Since the version 1.20.0, mypy reported many error about RoundingMethod:
```
tests/test_timestamps.py:18: error: Argument 1 to "FPSTimestamps" has incompatible type "Callable[[Fraction], int]"; expected "RoundingMethod"  [arg-type]
```

This happened since they properly added support for @enum.member (https://docs.python.org/3/library/enum.html#enum.member).

But, since @enum.member is only available since python 3.11, we need a workaround to fix mypy error.